# Generated by Django 5.2.1 on 2025-09-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_clientodoostatus_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsodoo',
            name='is_prelium',
            field=models.BooleanField(default=False, help_text='Cocher si ce client fait partie de la filiale Prelium.', verbose_name='Filiale Prelium'),
        ),
    ]
