# Generated by Django 5.2.1 on 2025-10-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_clientsodoo_is_prelium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('collaborateur', 'Collaborateur'), ('super_admin', 'Super Administrateur')], max_length=20, verbose_name='Rôle dans OdooDash'),
        ),
    ]
