# Generated by Django 5.2.1 on 2025-10-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsodoo',
            name='client_contact_email',
            field=models.EmailField(blank=True, help_text="L'adresse e-mail du client qui aura accès au dashboard Looker Studio.", max_length=254, null=True, verbose_name='E-mail du Contact Client (pour Looker Studio)'),
        ),
    ]
