# Generated by Django 5.2.1 on 2025-12-01 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_clientsodoo_client_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='client_odoo_link',
            field=models.ForeignKey(blank=True, help_text="Uniquement pour le rôle 'Client'. Définit quel dossier cet utilisateur peut voir.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clientsodoo', verbose_name='Dossier Client Associé'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('collaborateur', 'Collaborateur'), ('super_admin', 'Super Administrateur'), ('client', 'Client (Vue Dossier)')], max_length=20, verbose_name='Rôle dans OdooDash'),
        ),
    ]
