# Generated by Django 5.2.1 on 2025-12-02 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_userprofile_client_odoo_link_alter_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_indicators', models.JSONField(default=list, verbose_name='Indicateurs Visibles')),
                ('default_period', models.IntegerField(default=30, verbose_name='Période par défaut (jours)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.userprofile', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence Client',
                'verbose_name_plural': 'Préférences Clients',
            },
        ),
    ]
