"""
Django settings for OdooDash_project project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/stable/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/stable/ref/settings/
"""

from pathlib import Path
import os
import io
import dj_database_url
from dotenv import load_dotenv

# --- CONFIGURATION POUR LA PRODUCTION (GOOGLE CLOUD RUN & SECRET MANAGER) ---
# Essayer d'importer les bibliothèques Google Cloud.
try:
    import google.auth
    from google.cloud import secretmanager
    from google.api_core.exceptions import NotFound, PermissionDenied
    # Charger les variables d'environnement depuis Secret Manager si on est sur Cloud Run
    # La variable d'environnement GOOGLE_CLOUD_PROJECT est automatiquement définie sur Cloud Run
    if os.environ.get("GOOGLE_CLOUD_PROJECT"):
        print("INFO: Environnement Google Cloud détecté. Tentative de chargement depuis Secret Manager...")
        try:
            _, project_id = google.auth.default()
            client = secretmanager.SecretManagerServiceClient()
            
            # Le nom du secret est passé via une variable d'environnement lors du déploiement
            settings_name = os.environ.get("SETTINGS_NAME", "django-settings")
            
            name = f"projects/{project_id}/secrets/{settings_name}/versions/latest"
            payload = client.access_secret_version(name=name).payload.data.decode("UTF-8")
            
            # Charger les variables du secret dans l'environnement
            load_dotenv(stream=io.StringIO(payload))
            print("INFO: Variables d'environnement chargées avec succès depuis Secret Manager.")

        except (NotFound, PermissionDenied) as e:
            print(f"AVERTISSEMENT: Impossible de charger le secret '{settings_name}'. Erreur: {e}. L'application pourrait ne pas fonctionner correctement en production.")
        except Exception as e:
            print(f"ERREUR: Une erreur inattendue est survenue lors du chargement des secrets : {e}")
            
except ImportError:
    print("INFO: Les bibliothèques Google Cloud ne sont pas installées. Passage en mode développement local.")
    pass

# --- CONFIGURATION DE DÉVELOPPEMENT LOCAL (FALLBACK) ---
# Charger les variables d'environnement depuis le fichier .env si elles n'ont pas déjà été chargées
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/stable/howto/deployment/checklist/

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-for-dev')
DEBUG = os.getenv('DEBUG', 'True') == 'True'


# Configuration des hôtes autorisés
K_SERVICE = os.environ.get('K_SERVICE')
if K_SERVICE: # Nous sommes en production sur Cloud Run
    ALLOWED_HOSTS = ['.run.app'] # Accepte tous les sous-domaines de run.app
    CSRF_TRUSTED_ORIGINS = [f'https://{K_SERVICE}-{os.environ.get("GOOGLE_CLOUD_PROJECT_NUMBER")}-{os.environ.get("GOOGLE_CLOUD_REGION_CODE")}.run.app']
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
else: # Nous sommes en développement local
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']


# --- Clé de Chiffrement ---
FERNET_KEY = os.getenv('FERNET_KEY')
if not FERNET_KEY and DEBUG:
    print("ATTENTION : FERNET_KEY n'est pas définie dans l'environnement !")
elif not FERNET_KEY and not DEBUG:
    raise ValueError("La clé de chiffrement FERNET_KEY est manquante dans l'environnement de production.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core', # Votre application
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # Ajout de Whitenoise
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'OdooDash_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OdooDash_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/stable/ref/settings/#databases
# La configuration utilise dj_database_url pour lire la variable DATABASE_URL
# de Secret Manager (en prod) ou du fichier .env (en local).

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL', 'sqlite:///' + str(BASE_DIR / 'db.sqlite3')),
        conn_max_age=600 # Recommandé pour les bases de données en production
    )
}


# Password validation
# https://docs.djangoproject.com/en/stable/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    { 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    { 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator', },
]


# Internationalization
# https://docs.djangoproject.com/en/stable/topics/i18n/

LANGUAGE_CODE = 'fr-fr'
TIME_ZONE = 'Europe/Paris'
USE_I18N = True
USE_L10N = True # Correction de USE_FORMAT_L10N en USE_L10N pour les versions récentes
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/stable/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles' # Dossier pour collectstatic
STATICFILES_DIRS = [
    BASE_DIR / "static", # Ajout pour que Django trouve votre dossier static/core en développement
]

# Configuration de Whitenoise pour la production
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/stable/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Authentification Settings ---
LOGIN_REDIRECT_URL = '/app/dashboard/'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
# --- Fin Authentification ---

